c3p0:
  datasource:
    max-pool-size: 20
    min-pool-size: 1
    max-idle-time: 60
    test-connection-on-checkout: false
    test-connection-on-checkin: true
    idle-connection-test-period: 30
spring:
  application:
    name: movies
  jackson.serialization:
    write-dates-as-timestamps: false
management.context-path: /manage
app.compraentradas:
  url-to-list-movies: http://www.compraentradas.com/
  css-query-to-list-movies: '#SelectPeliculas>option'
  